### ISSUE TITLE
Interface change of `target_manager`

### ISSUE THREAD

**Issue by icsl-Jeon** [LARR-Planning/los-keeper#17]
In your code `target_manager`, 
There is no extractor of Prediction Result (e.g., `GetTargetPredictionTrajectory()`)
You should change into either one of two:
1.  Change `bool PredictTargetTrajectory() override;` -> `Trajectory PredictTargetTrajectory(some input) const` 
2.  Add  `GetTargetPredictionTrajectory() const`

**Comment by icsl-Jeon** [comment]
Also, what is the type of target prediction? Is it StatePoly?
@YunwooLee94

**Comment by YunwooLee94** [comment]
I want to modify the result type of Target Prediction to std::vector<StatePoly> because I want to include cases where multiple targets are handled.

**Comment by icsl-Jeon** [comment]
This is already implemented. Vectorized output. Please check master branch

**Comment by YunwooLee94** [comment]
Got it. Thx:)
