### ISSUE TITLE
Combine Set -> Do -> Get into a single function?

### ISSUE THREAD

**Issue by icsl-Jeon** [LARR-Planning/los-keeper#19]
In your implementation, there are setters -> do (PredictTargetTrajectory)-> getter process.  
```cpp
  void SetTargetState(const std::vector<ObjectState> &target_state_list);
  void SetObstacleState(pcl::PointCloud<pcl::PointXYZ> cloud,
                        std::vector<StatePoly> structured_obstacle_poly_list);
  virtual bool PredictTargetTrajectory() = 0;

  StatePoly GetTargetPrediction() const;
```

How about combine them into the single function ? 

```cpp 
std::optional<StatePoly> PredictTargetTrajectory(const std::vector<ObjectState> &target_state_list, pcl::PointCloud<pcl::PointXYZ> cloud, std::vector<StatePoly> structured_obstacle_poly_list);
```

Because, I could not find any reason for target manager to hold obstacle information as its member variables

**Comment by icsl-Jeon** [comment]
Here is the [example](https://github.com/LARR-Planning/los-keeper/blob/90968edfea5944be88a54efcb7d8aa1ae58cfec1/los_keeper/include/los_keeper/target_manager/target_manager.h#L59)

**Comment by YunwooLee94** [comment]
Thank you for telling me. However, I have a concern. I will ask about it later after organizing my thoughts.
