### ISSUE TITLE
Interface functions in wrapper.cc

### ISSUE THREAD

**Issue by YunwooLee94** [LARR-Planning/los-keeper#23]
After the merging branch "utils_arrange" into "master", I plan to change functions in target_manager.h/cc and trajectory_planner.h/cc.
In wrapper.cc, you used the following functions 
`PredictTargetList(const std::vector<ObjectState> &target_state_list,
                    const PclPointCloud &point_cloud,
                    const std::vector<StatePoly> &structured_obstacle_poly_list)`

I will fill the codes in the function so that this function can be executed successfully.

So far, I have implemented the USG structure you mentioned by adding the following functions to 'target_manager.h': 1. Set: (e.g., SetTargetState(...)), 2. Update: (e.g., PredictTargetTrajectory()), 3. Get: (GetTargetPredictionResult()).
I will insert the functions I made into the functions you provided in the order of Set, Update, and Get.

In addition, you mentioned that the variables regarding obstacle information in target_manager.h is redundant.
I understand what you said. If you feel uncomfortable i am gonna remove that variables.

**Comment by icsl-Jeon** [comment]
Regarding this, I have a word.! Let me write soon

**Comment by YunwooLee94** [comment]
This also has been discussed, and I will reflect the points of discussion.
Close this issue.
