### ISSUE TITLE
Parameter Settings

### ISSUE THREAD

**Issue by YunwooLee94** [LARR-Planning/los-keeper#24]
struct PredictionParam{
	int num_sample; // The number of primitives
	int num_thread; // The number of threads used in Prediction
	float planning_horizon; // The time horizon
	float acc_max; // The maximum acceleration of the targets
	float detect_range; // Range of consideration of structured obstacles.
	float virtual_pcl_zone_width_; // Range of virtual pcl to make SFC (width)
  float virtual_pcl_zone_height_; // Range of virtual pcl to make SFC (height)
  bool is_lite; // Lite vs Pro version, TODO: Only Pro version is implemented currently. 
};

struct PlanningParam{
  int num_sample; // The number of primitives
  int num_thread; // The number of threads used in Planning
  float target_distance_min;	// Minimum distance between the target and the drone.
  float target_distance_max;	// Maximum distance between the target and the drone.
  float planning_horizon;	// The time horizon
	float vel_max; // Maximum velocity
  float acc_max;	// Maximum acceleartion
  float fov_angle; // FOV angle
  float rx; // Drone radius (x-axis)
  float ry; // Drone radius (y-axis)
  float rz; // Drone radius (z-axis)
  float virtual_pcl_zone_width_; // Range of virtual pcl to make SFC (width)
  float virtual_pcl_zone_height_; // Range of virtual pcl to make SFC (height)
  bool is_lite; // Lite vs Pro version, TODO: Only Pro version is implemented currently. 
};

struct ProblemParam{
	bool is_2d; // "true" if 2d scenarios and "false" if 3d scenarios
};

The above are parameters that are used in Prediction and Planning.
Should I add them in 'type_manager.h'?

**Comment by icsl-Jeon** [comment]
No! I think parameters should be encapsulated to each class, which will
be received by wrapper at the construction of each class! ;)

**Comment by YunwooLee94** [comment]
@icsl-Jeon  Then, how can wrapper deliver parameters to each class?

**Comment by icsl-Jeon** [comment]
If our discussion answers, please close issue!

**Comment by YunwooLee94** [comment]
:) close this issue.
