### ISSUE TITLE
Making your tests for collision check

### ISSUE THREAD

**Issue by icsl-Jeon** [LARR-Planning/los-keeper#27]
Good morning @YunwooLee94. 
I think it is a perfect time for you to create your first testing in `obstacle_manager_test.cc` when you are working with collision checker (maybe public). 
If you have some time, how about trying it? 
I can help you if you have any question.

**Comment by icsl-Jeon** [comment]
When you are working with test, you should open core project only with CLion. 3

**Comment by YunwooLee94** [comment]
Thank you:):)
I'll try it tomorrow
