### ISSUE TITLE
Parameters in struct

### ISSUE THREAD

**Issue by YunwooLee94** [LARR-Planning/los-keeper#30]
https://github.com/LARR-Planning/los-keeper/blob/ac81dc07af3f13b5a41565421cfb952ea3e59064/los_keeper/include/los_keeper/type_manager/type_manager.h#L14-L65

Is this equal to what you thought? @icsl-Jeon

**Comment by YunwooLee94** [comment]
Also I added namespace "Parameters" for these structs.

**Comment by icsl-Jeon** [comment]
Not really, as I said,
`Parameters{
struct {
double width{1.0};
double height{1.0};
} sfc;
}` this will work.

More specifically,

`struct{struct{ int param_a{1}; int param_b{2}} sfc_parameter} Parameters` this definition.
By this, you can declare a param `Parameters parameters_` and you can access by `parameters_.sfc_parameter.param_a`

**Comment by YunwooLee94** [comment]
Thx:)
Thank you for the kind explanation and examples.
I understood what you said, but CLion told the approaches make error temporarily.
So I have tried to find different way. TT

Anyway..
struct Parameters{ struct { double width{1.0}; double height{1.0}; } sfc; };
This code works well.

**Comment by icsl-Jeon** [comment]
Good ! anyway, it is okay if you can `parameters.sfc.width`
