### ISSUE TITLE
Set parameters via yaml.

### ISSUE THREAD

**Issue by YunwooLee94** [LARR-Planning/los-keeper#31]
Could you give me advice about parameter settings with class instantiation?

In addition to existing Wrapper::Wrapper(), I made another constructors. I want to implement tasks (functions) in new one.

https://github.com/LARR-Planning/los-keeper/blob/7632745c52ac9b08c2e61eb4064ef8d0769db7c8/los_keeper/src/wrapper/wrapper.cc#LL4C1-L21C2

With the implemented parameter setting, can we use Wrapper::Wrapper()? The below is where the LosServer loads parameters.

https://github.com/LARR-Planning/los-keeper/blob/7632745c52ac9b08c2e61eb4064ef8d0769db7c8/los_keeper_ros2/src/los_server/los_server.cc#L42-L118

**Comment by icsl-Jeon** [comment]
How about making a public functions to each class : LoadParameters(Parameter parameter) ?

**Comment by YunwooLee94** [comment]
https://github.com/LARR-Planning/los-keeper/blob/7632745c52ac9b08c2e61eb4064ef8d0769db7c8/los_keeper/src/wrapper/wrapper.cc#LL11C1-L21C2

My main concern is ...
since the problem-solving for 2D and 3D problems is divided into classes, would it be sufficient to solve it simply by using "LoadParameters(Parameter parameter)"?

**Comment by icsl-Jeon** [comment]
My point in the line was:
Dimension params should be available in the level of wrapper. 
But once dimension is set, then LoadParam or whatever you want!
