### ISSUE TITLE
Visualization of intermediate results.

### ISSUE THREAD

**Issue by YunwooLee94** [LARR-Planning/los-keeper#34]
You know that the functions that wrapper can only use from core class (ex. TargetManager) is PredictTargetList(...).

https://github.com/LARR-Planning/los-keeper/blob/4a2e59a254acbcbdf71f0ec141b66de7697f1711/los_keeper/include/los_keeper/target_manager/target_manager.h#L134-L137

In the prediction process, until obtaining the best path, motion primitives are calculated and collision checks are performed, resulting in various kinds of intermediate results. What would be a good approach to accessing these intermediate results from the outside (wrapper)?

**Comment by YunwooLee94** [comment]
Oh I see. Thx:)
It looks like we can update the debug information along with the update of the plan result.

**Comment by YunwooLee94** [comment]
Can I ask you to handle this work too?

**Comment by icsl-Jeon** [comment]
Which part did you find difficult?
