### ISSUE TITLE
Bug found in `PredictTarget(...)`

### ISSUE THREAD

**Issue by icsl-Jeon** [LARR-Planning/los-keeper#41]
`reserve` operation does not resize the vector ([here](https://director-joe.kr/27)).
I told that you should have tested every procedure by gtesting.
 
![image](https://github.com/LARR-Planning/los-keeper/assets/30062474/afc213c5-b6dc-4ad4-9c3f-74967ec176f8)

**Comment by YunwooLee94** [comment]
Thx for notice. 
I wasn't sure about the usage of "resize" and "reserve", so I planned to check later. 
I did make a note in my TODO list as well. 
I agree that it would have been better to use gtest to check beforehand, as you suggested.

**Comment by icsl-Jeon** [comment]
Another problem, 
```cpp
void TrajectoryPlanner3D::SampleShootingPointsSubProcess(const int &target_id,
                                                         const int &chunk_size,
                                                         PointList &shooting_points_sub) {
  Point end_point_center{target_trajectory_list_[target_id].px.GetTerminalValue(),
                         target_trajectory_list_[target_id].py.GetTerminalValue(),
                         target_trajectory_list_[target_id].pz.GetTerminalValue()};
```
In this code, you do not check the validity of `target_trajectory_list_[target_id]` (i.e., valid coefficient array)
