### ISSUE TITLE
Wrapper Test

### ISSUE THREAD

**Issue by YunwooLee94** [LARR-Planning/los-keeper#48]
https://github.com/LARR-Planning/los-keeper/blob/65bf3db94fe6344f483e2f75240b332c12ed292b/los_keeper/test/wrapper_test.cc#L177-L180
`wrapper_.OnPlanningTimerCallback()` increases the value of `wrapper_.planning_result_.seq` each time it is executed. Therefore, I changed `EXPECT_EQ` to `EXPECT_GT` currently.

Could you check this?

**Comment by icsl-Jeon** [comment]
Planning should not be triggered in this case. I already commented..
Your saying is not correct. This should be equal.
